name: Deploy Hello World App

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: 684882368970
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - id: 'auth'
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{env.AWS_REGION}}
      
      - name: Get ECR login password
        id: ecr-login
        run: echo "::set-output name=password::$(aws ecr get-login-password --region ${{env.AWS_REGION}})"

      - name: Check ECR authentication
        run: docker login -u AWS -p ${{ steps.ecr-login.outputs.password }} ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com
        
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com
          username: AWS
          password: ${{ steps.ecr-login.outputs.password }}

      - name: Push Docker image to ECR
        run: |
          docker build -t ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/my-ecr-repo:${{ github.sha }} .
          docker push ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/my-ecr-repo:${{ github.sha }}
          
      - name: Deploy to Cloud Run
        run: |
          terraform init -input=true
          terraform state list
          terraform plan -var="image_tag=${{ github.sha }}"
          terraform apply -var="image_tag=${{ github.sha }}" -auto-approve
